server:
  port: 8008
spring:
  application:
    name: system
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      context-path: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_sample?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      initial-size: 3 #初始化时建立物理连接的个数
      minIdle: 3 #最小连接池数量
      maxActive: 50 #最大连接池数量
      maxWait: 60000 #获取连接的最大等待时间，毫秒
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，毫秒
      minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，毫秒
      maxEvictableIdleTimeMillis: 900000 #配置一个连接在池中最大生存的时间，毫秒
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'
      validationQuery: select 'x'
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      poolPreparedStatements: true
      filter:
        stat:
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info
    com.sdwfqin: debug
  config: classpath:logback-spring.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO

#暴露健康监测接口给admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      enabled: true
      external-file: logs/system/output.log

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/auth/user/current
    client:
      client-id: service
      client-secret: sdwfqin
      access-token-uri: http://localhost:8002/auth/oauth/token
      user-authorization-uri: http://localhost:8002/auth/oauth/authorize
      scope: service
